repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.4.5
  hooks:
  - id: nbdev_clean
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.9
  hooks:
  - id: ruff
    name: ruff-check
    args: [--fix]
    exclude: ^notebooks/
  - id: ruff-format
    name: ruff-format
    exclude: ^notebooks/
