services:
  langtree:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        UBUNTU_VERSION: "24.04"
        USER: "${USER}"
        USER_UID: "1000"
        USER_GID: "1000"
        UV_VERSION: "0.8.22"
        NODE_VERSION: "v0.40.3"
        NVM_VERSION: "24.9.0"
        PROJDIR: /workspaces/langtree
        PROJECT_NAME: langtree
    env_file:
      - /home/${USER}/credentials/my.apikeys.env
    command: sleep infinity
    volumes:
      - ..:/workspaces/langtree:cached
      - /home/${USER}/.bash_history:/home/${USER}/.bash_history
      - /home/${USER}/.cache:/home/${USER}/.cache
      - /home/${USER}/credentials/my.apikeys.env:/home/${USER}/credentials/my.apikeys.env
      # Claude Code:
      - /home/${USER}/.claude:/home/${USER}/.claude
      - /home/${USER}/.config/claude-code/:/home/${USER}/.config/claude-code/
